version: '3.8'

services:
  web:
    image: wilgnne/openstreaming-web:latest
    restart: unless-stopped
    networks:
      - open-streaming
      - traefik_public
    labels:
      - traefik.enable=true
      - traefik.http.services.openstreaming-web.loadbalancer.server.port=3000
      - traefik.http.routers.openstreaming-web.entrypoints=http
      - traefik.http.routers.openstreaming-web.rule=Host(`openstreaming.wilgnne.dev`)

  hls_nginx:
    image: nginx:stable
    restart: unless-stopped
    networks:
      - open-streaming
      - traefik_public
    volumes:
      - ./hls_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - hls_streaming:/hls_streaming
    labels:
      - traefik.enable=true
      - traefik.http.services.openstreaming-hls_nginx.loadbalancer.server.port=80
      - traefik.http.routers.openstreaming-hls_nginx.entrypoints=http
      - traefik.http.routers.openstreaming-hls_nginx.rule=Host(`openstreaming-hls.wilgnne.dev`)

  hls_streaming:
    image: linuxserver/ffmpeg:latest
    restart: unless-stopped
    entrypoint: "ffmpeg -stream_loop -1 -re -i /input.mp4 -c copy -strict -2 -f hls -hls_time 1 -hls_list_size 15 -hls_flags delete_segments+append_list+split_by_time /hls_streaming/output.m3u8"
    volumes:
      - ./hls_streaming/Blender_4.0-Reel-(1080p).mp4:/input.mp4
      - hls_streaming:/hls_streaming
    deploy:
      resources:
        limits:
          cpus: '0.2'

volumes:
  hls_streaming:


networks:
  open-streaming:
  traefik_public:
    external: true
